module StartingPositions
  STARTING_POSITIONS = [

    ChessPiece.new(:white, :rook, Position.new(0, 0)),
    ChessPiece.new(:white, :knight, Position.new(1, 0)),
    ChessPiece.new(:white, :bishop, Position.new(2, 0)),
    ChessPiece.new(:white, :queen, Position.new(3, 0)),
    ChessPiece.new(:white, :king, Position.new(4, 0)),
    ChessPiece.new(:white, :bishop, Position.new(5, 0)),
    ChessPiece.new(:white, :knight, Position.new(6, 0)),
    ChessPiece.new(:white, :rook, Position.new(7, 0)),
    ChessPiece.new(:white, :pawn, Position.new(0, 1)),
    ChessPiece.new(:white, :pawn, Position.new(1, 1)),
    ChessPiece.new(:white, :pawn, Position.new(2, 1)),
    ChessPiece.new(:white, :pawn, Position.new(3, 1)),
    ChessPiece.new(:white, :pawn, Position.new(4, 1)),
    ChessPiece.new(:white, :pawn, Position.new(5, 1)),
    ChessPiece.new(:white, :pawn, Position.new(6, 1)),
    ChessPiece.new(:white, :pawn, Position.new(7, 1)),
    ChessPiece.new(:black, :pawn, Position.new(0, 6)),
    ChessPiece.new(:black, :pawn, Position.new(1, 6)),
    ChessPiece.new(:black, :pawn, Position.new(2, 6)),
    ChessPiece.new(:black, :pawn, Position.new(3, 6)),
    ChessPiece.new(:black, :pawn, Position.new(4, 6)),
    ChessPiece.new(:black, :pawn, Position.new(5, 6)),
    ChessPiece.new(:black, :pawn, Position.new(6, 6)),
    ChessPiece.new(:black, :pawn, Position.new(7, 6)),
    ChessPiece.new(:black, :rook, Position.new(0, 7)),
    ChessPiece.new(:black, :knight, Position.new(1, 7)),
    ChessPiece.new(:black, :bishop, Position.new(2, 7)),
    ChessPiece.new(:black, :queen, Position.new(3, 7)),
    ChessPiece.new(:black, :king, Position.new(4, 7)),
    ChessPiece.new(:black, :bishop, Position.new(5, 7)),
    ChessPiece.new(:black, :knight, Position.new(6, 7)),
    ChessPiece.new(:black, :rook, Position.new(7, 7)),

  ]
end
