module StartingPositions
  STARTING_POSITIONS = [

    ChessPiece.new(:white, :rook, Position.new(0, 0)),
    ChessPiece.new(:white, :knight, Position.new(0, 1)),
    ChessPiece.new(:white, :bishop, Position.new(0, 2)),
    ChessPiece.new(:white, :queen, Position.new(0, 3)),
    ChessPiece.new(:white, :king, Position.new(0, 4)),
    ChessPiece.new(:white, :bishop, Position.new(0, 5)),
    ChessPiece.new(:white, :knight, Position.new(0, 6)),
    ChessPiece.new(:white, :rook, Position.new(0, 7)),
    ChessPiece.new(:white, :pawn, Position.new(1, 0)),
    ChessPiece.new(:white, :pawn, Position.new(1, 1)),
    ChessPiece.new(:white, :pawn, Position.new(1, 2)),
    ChessPiece.new(:white, :pawn, Position.new(1, 3)),
    ChessPiece.new(:white, :pawn, Position.new(1, 4)),
    ChessPiece.new(:white, :pawn, Position.new(1, 5)),
    ChessPiece.new(:white, :pawn, Position.new(1, 6)),
    ChessPiece.new(:white, :pawn, Position.new(1, 7)),
    ChessPiece.new(:black, :pawn, Position.new(6, 0)),
    ChessPiece.new(:black, :pawn, Position.new(6, 1)),
    ChessPiece.new(:black, :pawn, Position.new(6, 2)),
    ChessPiece.new(:black, :pawn, Position.new(6, 3)),
    ChessPiece.new(:black, :pawn, Position.new(6, 4)),
    ChessPiece.new(:black, :pawn, Position.new(6, 5)),
    ChessPiece.new(:black, :pawn, Position.new(6, 6)),
    ChessPiece.new(:black, :pawn, Position.new(6, 7)),
    ChessPiece.new(:black, :rook, Position.new(7, 0)),
    ChessPiece.new(:black, :knight, Position.new(7, 1)),
    ChessPiece.new(:black, :bishop, Position.new(7, 2)),
    ChessPiece.new(:black, :queen, Position.new(7, 3)),
    ChessPiece.new(:black, :king, Position.new(7, 4)),
    ChessPiece.new(:black, :bishop, Position.new(7, 5)),
    ChessPiece.new(:black, :knight, Position.new(7, 6)),
    ChessPiece.new(:black, :rook, Position.new(7, 7)),

  ]
end
