inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - app/services/*
    - spec/services/*
    - app/controllers/*
    - spec/controllers/*
    - spec/helpers/*
    - spec/models/*
    - config/initializers/*
  DisplayCopNames: true

ClassLength:
  Max: 125

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

StringLiterals:
  Enabled: false
